name: Sync Google Reviews

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Reviews
        run: curl -s -f -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" "https://upcars-v2.vercel.app/api/cron/reviews"
