name: Hourly Tasks

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  sla:
    runs-on: ubuntu-latest
    steps:
      - name: Check SLAs
        run: curl -s -f "https://upcars-v2-ka37nuu0f-franciscoinostrozaa-7344s-projects.vercel.app/api/cron/sla"

  alerts:
    needs: sla
    runs-on: ubuntu-latest
    steps:
      - name: Check Alerts
        run: curl -s -f "https://upcars-v2-ka37nuu0f-franciscoinostrozaa-7344s-projects.vercel.app/api/cron/alerts"
